name: Sync Remote Files

on:
  schedule:
    # Run weekly at 02:00 UTC on Sundays
    - cron: '0 2 * * 0'
  workflow_dispatch: # Allow manual triggers

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Configure git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      
      - name: Run remote sync
        run: npm run sync:remote
      
      - name: Check for changes
        id: changes
        run: |
          git add -A
          if git diff --staged --quiet; then
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi
      
      - name: Create Pull Request
        if: steps.changes.outputs.has_changes == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "🤖 Auto-sync: Update remote llms.txt files"
          title: "🤖 Weekly sync: Update remote llms.txt files"
          body: |
            ## Automated Remote Sync
            
            This PR was automatically generated by the weekly sync workflow.
            
            **Changes:**
            - Updated llms.txt files from public directories
            - Source sites: llmstxt.site, directory.llmstxt.cloud
            
            **Review checklist:**
            - [ ] Check that file contents look reasonable
            - [ ] Verify no sensitive information was included
            - [ ] Confirm token counts are updated
            
            _Generated on: ${{ github.run_id }}_
          branch: sync/auto-update-${{ github.run_number }}
          delete-branch: true
          draft: false
      
      - name: Log results
        run: |
          if [[ "${{ steps.changes.outputs.has_changes }}" == "true" ]]; then
            echo "✅ Changes detected and PR created"
          else
            echo "ℹ️ No changes detected"
          fi